// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_GetMe_FullMethodName            = "/auth.AuthService/GetMe"
	AuthService_SignupClient_FullMethodName     = "/auth.AuthService/SignupClient"
	AuthService_ListClientUsers_FullMethodName  = "/auth.AuthService/ListClientUsers"
	AuthService_GetClientUser_FullMethodName    = "/auth.AuthService/GetClientUser"
	AuthService_CreateClientUser_FullMethodName = "/auth.AuthService/CreateClientUser"
	AuthService_UpdateClientUser_FullMethodName = "/auth.AuthService/UpdateClientUser"
	AuthService_DeleteClientUser_FullMethodName = "/auth.AuthService/DeleteClientUser"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService 認証サービス
type AuthServiceClient interface {
	// GetMe 現在のユーザー情報を取得（認証必要）
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error)
	// SignupClient サービス利用開始時のアカウント登録（認証不要）
	// 新規クライアント（企業）を登録し、同時にそのクライアントの管理者権限を持つユーザーを作成
	SignupClient(ctx context.Context, in *SignupClientRequest, opts ...grpc.CallOption) (*SignupClientResponse, error)
	// クライアントユーザー管理
	// ListClientUsers クライアントユーザー一覧取得（認証必要、権限: users:READ）
	ListClientUsers(ctx context.Context, in *ListClientUsersRequest, opts ...grpc.CallOption) (*ListClientUsersResponse, error)
	// GetClientUser クライアントユーザー詳細取得（認証必要、権限: users:READ）
	GetClientUser(ctx context.Context, in *GetClientUserRequest, opts ...grpc.CallOption) (*GetClientUserResponse, error)
	// CreateClientUser クライアントユーザー作成（認証必要、権限: users:WRITE）
	CreateClientUser(ctx context.Context, in *CreateClientUserRequest, opts ...grpc.CallOption) (*CreateClientUserResponse, error)
	// UpdateClientUser クライアントユーザー更新（認証必要、権限: users:WRITE）
	UpdateClientUser(ctx context.Context, in *UpdateClientUserRequest, opts ...grpc.CallOption) (*UpdateClientUserResponse, error)
	// DeleteClientUser クライアントユーザー削除（認証必要、権限: users:DELETE）
	DeleteClientUser(ctx context.Context, in *DeleteClientUserRequest, opts ...grpc.CallOption) (*DeleteClientUserResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeResponse)
	err := c.cc.Invoke(ctx, AuthService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SignupClient(ctx context.Context, in *SignupClientRequest, opts ...grpc.CallOption) (*SignupClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupClientResponse)
	err := c.cc.Invoke(ctx, AuthService_SignupClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListClientUsers(ctx context.Context, in *ListClientUsersRequest, opts ...grpc.CallOption) (*ListClientUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientUsersResponse)
	err := c.cc.Invoke(ctx, AuthService_ListClientUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetClientUser(ctx context.Context, in *GetClientUserRequest, opts ...grpc.CallOption) (*GetClientUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientUserResponse)
	err := c.cc.Invoke(ctx, AuthService_GetClientUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateClientUser(ctx context.Context, in *CreateClientUserRequest, opts ...grpc.CallOption) (*CreateClientUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClientUserResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateClientUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateClientUser(ctx context.Context, in *UpdateClientUserRequest, opts ...grpc.CallOption) (*UpdateClientUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateClientUserResponse)
	err := c.cc.Invoke(ctx, AuthService_UpdateClientUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteClientUser(ctx context.Context, in *DeleteClientUserRequest, opts ...grpc.CallOption) (*DeleteClientUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteClientUserResponse)
	err := c.cc.Invoke(ctx, AuthService_DeleteClientUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService 認証サービス
type AuthServiceServer interface {
	// GetMe 現在のユーザー情報を取得（認証必要）
	GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error)
	// SignupClient サービス利用開始時のアカウント登録（認証不要）
	// 新規クライアント（企業）を登録し、同時にそのクライアントの管理者権限を持つユーザーを作成
	SignupClient(context.Context, *SignupClientRequest) (*SignupClientResponse, error)
	// クライアントユーザー管理
	// ListClientUsers クライアントユーザー一覧取得（認証必要、権限: users:READ）
	ListClientUsers(context.Context, *ListClientUsersRequest) (*ListClientUsersResponse, error)
	// GetClientUser クライアントユーザー詳細取得（認証必要、権限: users:READ）
	GetClientUser(context.Context, *GetClientUserRequest) (*GetClientUserResponse, error)
	// CreateClientUser クライアントユーザー作成（認証必要、権限: users:WRITE）
	CreateClientUser(context.Context, *CreateClientUserRequest) (*CreateClientUserResponse, error)
	// UpdateClientUser クライアントユーザー更新（認証必要、権限: users:WRITE）
	UpdateClientUser(context.Context, *UpdateClientUserRequest) (*UpdateClientUserResponse, error)
	// DeleteClientUser クライアントユーザー削除（認証必要、権限: users:DELETE）
	DeleteClientUser(context.Context, *DeleteClientUserRequest) (*DeleteClientUserResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedAuthServiceServer) SignupClient(context.Context, *SignupClientRequest) (*SignupClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignupClient not implemented")
}
func (UnimplementedAuthServiceServer) ListClientUsers(context.Context, *ListClientUsersRequest) (*ListClientUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClientUsers not implemented")
}
func (UnimplementedAuthServiceServer) GetClientUser(context.Context, *GetClientUserRequest) (*GetClientUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientUser not implemented")
}
func (UnimplementedAuthServiceServer) CreateClientUser(context.Context, *CreateClientUserRequest) (*CreateClientUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClientUser not implemented")
}
func (UnimplementedAuthServiceServer) UpdateClientUser(context.Context, *UpdateClientUserRequest) (*UpdateClientUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateClientUser not implemented")
}
func (UnimplementedAuthServiceServer) DeleteClientUser(context.Context, *DeleteClientUserRequest) (*DeleteClientUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteClientUser not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SignupClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignupClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SignupClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignupClient(ctx, req.(*SignupClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListClientUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListClientUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListClientUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListClientUsers(ctx, req.(*ListClientUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetClientUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetClientUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetClientUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetClientUser(ctx, req.(*GetClientUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateClientUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateClientUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateClientUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateClientUser(ctx, req.(*CreateClientUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateClientUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateClientUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdateClientUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateClientUser(ctx, req.(*UpdateClientUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteClientUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteClientUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_DeleteClientUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteClientUser(ctx, req.(*DeleteClientUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMe",
			Handler:    _AuthService_GetMe_Handler,
		},
		{
			MethodName: "SignupClient",
			Handler:    _AuthService_SignupClient_Handler,
		},
		{
			MethodName: "ListClientUsers",
			Handler:    _AuthService_ListClientUsers_Handler,
		},
		{
			MethodName: "GetClientUser",
			Handler:    _AuthService_GetClientUser_Handler,
		},
		{
			MethodName: "CreateClientUser",
			Handler:    _AuthService_CreateClientUser_Handler,
		},
		{
			MethodName: "UpdateClientUser",
			Handler:    _AuthService_UpdateClientUser_Handler,
		},
		{
			MethodName: "DeleteClientUser",
			Handler:    _AuthService_DeleteClientUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth/auth.proto",
}
