// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMeRequest 現在のユーザー情報取得リクエスト
type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{0}
}

// GetMeResponse 現在のユーザー情報取得レスポンス
type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // ユーザーID（UUID）
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                             // メールアドレス
	UserType      string                 `protobuf:"bytes,3,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`       // ユーザータイプ（OPERATOR or CLIENT_USER）
	ClientId      *string                `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"` // クライアントID（UUID、オプション）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMeResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetMeResponse) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *GetMeResponse) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

// SignupClientRequest サービス利用開始時のアカウント登録リクエスト
type SignupClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// クライアント情報
	Name                   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                            // クライアント名（必須）
	CompanyCode            *string `protobuf:"bytes,2,opt,name=company_code,json=companyCode,proto3,oneof" json:"company_code,omitempty"`                                     // 企業コード（オプション、JIPDEC標準企業コード、一意）
	Slug                   string  `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`                                                                            // スラッグ（必須、一意、サブドメイン用）
	ESignMode              *string `protobuf:"bytes,4,opt,name=e_sign_mode,json=eSignMode,proto3,oneof" json:"e_sign_mode,omitempty"`                                         // 電子署名方式（オプション、デフォルト: WITNESS_OTP）
	RetentionDefaultMonths *int32  `protobuf:"varint,5,opt,name=retention_default_months,json=retentionDefaultMonths,proto3,oneof" json:"retention_default_months,omitempty"` // データ保存期間（月、オプション、デフォルト: 84）
	Settings               *string `protobuf:"bytes,6,opt,name=settings,proto3,oneof" json:"settings,omitempty"`                                                              // 設定（JSON文字列、オプション、デフォルト: {}）
	// 管理者ユーザー情報
	AdminEmail      string  `protobuf:"bytes,10,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`                      // 管理者メールアドレス（必須）
	AdminPassword   string  `protobuf:"bytes,11,opt,name=admin_password,json=adminPassword,proto3" json:"admin_password,omitempty"`             // 管理者パスワード（必須）
	AdminFirstName  string  `protobuf:"bytes,12,opt,name=admin_first_name,json=adminFirstName,proto3" json:"admin_first_name,omitempty"`        // 管理者名（必須）
	AdminLastName   string  `protobuf:"bytes,13,opt,name=admin_last_name,json=adminLastName,proto3" json:"admin_last_name,omitempty"`           // 管理者姓（必須）
	AdminDepartment *string `protobuf:"bytes,14,opt,name=admin_department,json=adminDepartment,proto3,oneof" json:"admin_department,omitempty"` // 管理者部署（オプション）
	AdminPosition   *string `protobuf:"bytes,15,opt,name=admin_position,json=adminPosition,proto3,oneof" json:"admin_position,omitempty"`       // 管理者役職（オプション）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignupClientRequest) Reset() {
	*x = SignupClientRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupClientRequest) ProtoMessage() {}

func (x *SignupClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupClientRequest.ProtoReflect.Descriptor instead.
func (*SignupClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SignupClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignupClientRequest) GetCompanyCode() string {
	if x != nil && x.CompanyCode != nil {
		return *x.CompanyCode
	}
	return ""
}

func (x *SignupClientRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SignupClientRequest) GetESignMode() string {
	if x != nil && x.ESignMode != nil {
		return *x.ESignMode
	}
	return ""
}

func (x *SignupClientRequest) GetRetentionDefaultMonths() int32 {
	if x != nil && x.RetentionDefaultMonths != nil {
		return *x.RetentionDefaultMonths
	}
	return 0
}

func (x *SignupClientRequest) GetSettings() string {
	if x != nil && x.Settings != nil {
		return *x.Settings
	}
	return ""
}

func (x *SignupClientRequest) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *SignupClientRequest) GetAdminPassword() string {
	if x != nil {
		return x.AdminPassword
	}
	return ""
}

func (x *SignupClientRequest) GetAdminFirstName() string {
	if x != nil {
		return x.AdminFirstName
	}
	return ""
}

func (x *SignupClientRequest) GetAdminLastName() string {
	if x != nil {
		return x.AdminLastName
	}
	return ""
}

func (x *SignupClientRequest) GetAdminDepartment() string {
	if x != nil && x.AdminDepartment != nil {
		return *x.AdminDepartment
	}
	return ""
}

func (x *SignupClientRequest) GetAdminPosition() string {
	if x != nil && x.AdminPosition != nil {
		return *x.AdminPosition
	}
	return ""
}

// SignupClientResponse サービス利用開始時のアカウント登録レスポンス
type SignupClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`            // クライアントID（UUID）
	ClientName    string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`      // クライアント名
	AdminUserId   string                 `protobuf:"bytes,3,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"` // 管理者ユーザーID（UUID）
	AdminEmail    string                 `protobuf:"bytes,4,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`      // 管理者メールアドレス
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupClientResponse) Reset() {
	*x = SignupClientResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupClientResponse) ProtoMessage() {}

func (x *SignupClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupClientResponse.ProtoReflect.Descriptor instead.
func (*SignupClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SignupClientResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SignupClientResponse) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *SignupClientResponse) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

func (x *SignupClientResponse) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

// ListClientUsersRequest クライアントユーザー一覧取得リクエスト
type ListClientUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // 取得件数（デフォルト: 50、最大: 100）
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // オフセット（デフォルト: 0）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientUsersRequest) Reset() {
	*x = ListClientUsersRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientUsersRequest) ProtoMessage() {}

func (x *ListClientUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientUsersRequest.ProtoReflect.Descriptor instead.
func (*ListClientUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ListClientUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListClientUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListClientUsersResponse クライアントユーザー一覧取得レスポンス
type ListClientUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*ClientUser          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`  // ユーザー一覧
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 総件数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientUsersResponse) Reset() {
	*x = ListClientUsersResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientUsersResponse) ProtoMessage() {}

func (x *ListClientUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientUsersResponse.ProtoReflect.Descriptor instead.
func (*ListClientUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ListClientUsersResponse) GetUsers() []*ClientUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListClientUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetClientUserRequest クライアントユーザー詳細取得リクエスト
type GetClientUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientUserId  string                 `protobuf:"bytes,1,opt,name=client_user_id,json=clientUserId,proto3" json:"client_user_id,omitempty"` // クライアントユーザーID（UUID）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientUserRequest) Reset() {
	*x = GetClientUserRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientUserRequest) ProtoMessage() {}

func (x *GetClientUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientUserRequest.ProtoReflect.Descriptor instead.
func (*GetClientUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GetClientUserRequest) GetClientUserId() string {
	if x != nil {
		return x.ClientUserId
	}
	return ""
}

// GetClientUserResponse クライアントユーザー詳細取得レスポンス
type GetClientUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ClientUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientUserResponse) Reset() {
	*x = GetClientUserResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientUserResponse) ProtoMessage() {}

func (x *GetClientUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientUserResponse.ProtoReflect.Descriptor instead.
func (*GetClientUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *GetClientUserResponse) GetUser() *ClientUser {
	if x != nil {
		return x.User
	}
	return nil
}

// CreateClientUserRequest クライアントユーザー作成リクエスト
type CreateClientUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`                          // メールアドレス（必須）
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                    // パスワード（必須）
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"` // 名（必須）
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`    // 姓（必須）
	Department    *string                `protobuf:"bytes,5,opt,name=department,proto3,oneof" json:"department,omitempty"`          // 部署（オプション）
	Position      *string                `protobuf:"bytes,6,opt,name=position,proto3,oneof" json:"position,omitempty"`              // 役職（オプション）
	Settings      *string                `protobuf:"bytes,7,opt,name=settings,proto3,oneof" json:"settings,omitempty"`              // 設定（JSON文字列、オプション、デフォルト: {}）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientUserRequest) Reset() {
	*x = CreateClientUserRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientUserRequest) ProtoMessage() {}

func (x *CreateClientUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientUserRequest.ProtoReflect.Descriptor instead.
func (*CreateClientUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *CreateClientUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateClientUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateClientUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateClientUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateClientUserRequest) GetDepartment() string {
	if x != nil && x.Department != nil {
		return *x.Department
	}
	return ""
}

func (x *CreateClientUserRequest) GetPosition() string {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return ""
}

func (x *CreateClientUserRequest) GetSettings() string {
	if x != nil && x.Settings != nil {
		return *x.Settings
	}
	return ""
}

// CreateClientUserResponse クライアントユーザー作成レスポンス
type CreateClientUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ClientUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientUserResponse) Reset() {
	*x = CreateClientUserResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientUserResponse) ProtoMessage() {}

func (x *CreateClientUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientUserResponse.ProtoReflect.Descriptor instead.
func (*CreateClientUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *CreateClientUserResponse) GetUser() *ClientUser {
	if x != nil {
		return x.User
	}
	return nil
}

// UpdateClientUserRequest クライアントユーザー更新リクエスト
type UpdateClientUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientUserId  string                 `protobuf:"bytes,1,opt,name=client_user_id,json=clientUserId,proto3" json:"client_user_id,omitempty"` // クライアントユーザーID（UUID、必須）
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`                               // メールアドレス（オプション）
	FirstName     *string                `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`      // 名（オプション）
	LastName      *string                `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`         // 姓（オプション）
	Department    *string                `protobuf:"bytes,5,opt,name=department,proto3,oneof" json:"department,omitempty"`                     // 部署（オプション）
	Position      *string                `protobuf:"bytes,6,opt,name=position,proto3,oneof" json:"position,omitempty"`                         // 役職（オプション）
	Settings      *string                `protobuf:"bytes,7,opt,name=settings,proto3,oneof" json:"settings,omitempty"`                         // 設定（JSON文字列、オプション）
	Status        *string                `protobuf:"bytes,8,opt,name=status,proto3,oneof" json:"status,omitempty"`                             // ステータス（ACTIVE, INACTIVE, SUSPENDED、オプション）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientUserRequest) Reset() {
	*x = UpdateClientUserRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientUserRequest) ProtoMessage() {}

func (x *UpdateClientUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateClientUserRequest) GetClientUserId() string {
	if x != nil {
		return x.ClientUserId
	}
	return ""
}

func (x *UpdateClientUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateClientUserRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateClientUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateClientUserRequest) GetDepartment() string {
	if x != nil && x.Department != nil {
		return *x.Department
	}
	return ""
}

func (x *UpdateClientUserRequest) GetPosition() string {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return ""
}

func (x *UpdateClientUserRequest) GetSettings() string {
	if x != nil && x.Settings != nil {
		return *x.Settings
	}
	return ""
}

func (x *UpdateClientUserRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

// UpdateClientUserResponse クライアントユーザー更新レスポンス
type UpdateClientUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *ClientUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientUserResponse) Reset() {
	*x = UpdateClientUserResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientUserResponse) ProtoMessage() {}

func (x *UpdateClientUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateClientUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateClientUserResponse) GetUser() *ClientUser {
	if x != nil {
		return x.User
	}
	return nil
}

// DeleteClientUserRequest クライアントユーザー削除リクエスト
type DeleteClientUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientUserId  string                 `protobuf:"bytes,1,opt,name=client_user_id,json=clientUserId,proto3" json:"client_user_id,omitempty"` // クライアントユーザーID（UUID）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientUserRequest) Reset() {
	*x = DeleteClientUserRequest{}
	mi := &file_proto_auth_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientUserRequest) ProtoMessage() {}

func (x *DeleteClientUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteClientUserRequest) GetClientUserId() string {
	if x != nil {
		return x.ClientUserId
	}
	return ""
}

// DeleteClientUserResponse クライアントユーザー削除レスポンス
type DeleteClientUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientUserResponse) Reset() {
	*x = DeleteClientUserResponse{}
	mi := &file_proto_auth_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientUserResponse) ProtoMessage() {}

func (x *DeleteClientUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{13}
}

// ClientUser クライアントユーザー情報
type ClientUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientUserId  string                 `protobuf:"bytes,1,opt,name=client_user_id,json=clientUserId,proto3" json:"client_user_id,omitempty"` // クライアントユーザーID（UUID）
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`               // クライアントID（UUID）
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                     // メールアドレス
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`            // 名
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`               // 姓
	Department    *string                `protobuf:"bytes,6,opt,name=department,proto3,oneof" json:"department,omitempty"`                     // 部署
	Position      *string                `protobuf:"bytes,7,opt,name=position,proto3,oneof" json:"position,omitempty"`                         // 役職
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                                   // ステータス（ACTIVE, INACTIVE, SUSPENDED）
	Settings      string                 `protobuf:"bytes,9,opt,name=settings,proto3" json:"settings,omitempty"`                               // 設定（JSON文字列）
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`           // 作成日時（ISO 8601）
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`           // 更新日時（ISO 8601）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientUser) Reset() {
	*x = ClientUser{}
	mi := &file_proto_auth_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUser) ProtoMessage() {}

func (x *ClientUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUser.ProtoReflect.Descriptor instead.
func (*ClientUser) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ClientUser) GetClientUserId() string {
	if x != nil {
		return x.ClientUserId
	}
	return ""
}

func (x *ClientUser) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ClientUser) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ClientUser) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ClientUser) GetDepartment() string {
	if x != nil && x.Department != nil {
		return *x.Department
	}
	return ""
}

func (x *ClientUser) GetPosition() string {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return ""
}

func (x *ClientUser) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClientUser) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

func (x *ClientUser) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ClientUser) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_proto_auth_auth_proto protoreflect.FileDescriptor

const file_proto_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x15proto/auth/auth.proto\x12\x04auth\"\x0e\n" +
	"\fGetMeRequest\"\x8b\x01\n" +
	"\rGetMeResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tuser_type\x18\x03 \x01(\tR\buserType\x12 \n" +
	"\tclient_id\x18\x04 \x01(\tH\x00R\bclientId\x88\x01\x01B\f\n" +
	"\n" +
	"_client_id\"\xd3\x04\n" +
	"\x13SignupClientRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\fcompany_code\x18\x02 \x01(\tH\x00R\vcompanyCode\x88\x01\x01\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12#\n" +
	"\ve_sign_mode\x18\x04 \x01(\tH\x01R\teSignMode\x88\x01\x01\x12=\n" +
	"\x18retention_default_months\x18\x05 \x01(\x05H\x02R\x16retentionDefaultMonths\x88\x01\x01\x12\x1f\n" +
	"\bsettings\x18\x06 \x01(\tH\x03R\bsettings\x88\x01\x01\x12\x1f\n" +
	"\vadmin_email\x18\n" +
	" \x01(\tR\n" +
	"adminEmail\x12%\n" +
	"\x0eadmin_password\x18\v \x01(\tR\radminPassword\x12(\n" +
	"\x10admin_first_name\x18\f \x01(\tR\x0eadminFirstName\x12&\n" +
	"\x0fadmin_last_name\x18\r \x01(\tR\radminLastName\x12.\n" +
	"\x10admin_department\x18\x0e \x01(\tH\x04R\x0fadminDepartment\x88\x01\x01\x12*\n" +
	"\x0eadmin_position\x18\x0f \x01(\tH\x05R\radminPosition\x88\x01\x01B\x0f\n" +
	"\r_company_codeB\x0e\n" +
	"\f_e_sign_modeB\x1b\n" +
	"\x19_retention_default_monthsB\v\n" +
	"\t_settingsB\x13\n" +
	"\x11_admin_departmentB\x11\n" +
	"\x0f_admin_position\"\x99\x01\n" +
	"\x14SignupClientResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x12\"\n" +
	"\radmin_user_id\x18\x03 \x01(\tR\vadminUserId\x12\x1f\n" +
	"\vadmin_email\x18\x04 \x01(\tR\n" +
	"adminEmail\"F\n" +
	"\x16ListClientUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"W\n" +
	"\x17ListClientUsersResponse\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.auth.ClientUserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"<\n" +
	"\x14GetClientUserRequest\x12$\n" +
	"\x0eclient_user_id\x18\x01 \x01(\tR\fclientUserId\"=\n" +
	"\x15GetClientUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.auth.ClientUserR\x04user\"\x97\x02\n" +
	"\x17CreateClientUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12#\n" +
	"\n" +
	"department\x18\x05 \x01(\tH\x00R\n" +
	"department\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\x06 \x01(\tH\x01R\bposition\x88\x01\x01\x12\x1f\n" +
	"\bsettings\x18\a \x01(\tH\x02R\bsettings\x88\x01\x01B\r\n" +
	"\v_departmentB\v\n" +
	"\t_positionB\v\n" +
	"\t_settings\"@\n" +
	"\x18CreateClientUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.auth.ClientUserR\x04user\"\xff\x02\n" +
	"\x17UpdateClientUserRequest\x12$\n" +
	"\x0eclient_user_id\x18\x01 \x01(\tR\fclientUserId\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tH\x01R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x04 \x01(\tH\x02R\blastName\x88\x01\x01\x12#\n" +
	"\n" +
	"department\x18\x05 \x01(\tH\x03R\n" +
	"department\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\x06 \x01(\tH\x04R\bposition\x88\x01\x01\x12\x1f\n" +
	"\bsettings\x18\a \x01(\tH\x05R\bsettings\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\b \x01(\tH\x06R\x06status\x88\x01\x01B\b\n" +
	"\x06_emailB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\r\n" +
	"\v_departmentB\v\n" +
	"\t_positionB\v\n" +
	"\t_settingsB\t\n" +
	"\a_status\"@\n" +
	"\x18UpdateClientUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.auth.ClientUserR\x04user\"?\n" +
	"\x17DeleteClientUserRequest\x12$\n" +
	"\x0eclient_user_id\x18\x01 \x01(\tR\fclientUserId\"\x1a\n" +
	"\x18DeleteClientUserResponse\"\xf5\x02\n" +
	"\n" +
	"ClientUser\x12$\n" +
	"\x0eclient_user_id\x18\x01 \x01(\tR\fclientUserId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12#\n" +
	"\n" +
	"department\x18\x06 \x01(\tH\x00R\n" +
	"department\x88\x01\x01\x12\x1f\n" +
	"\bposition\x18\a \x01(\tH\x01R\bposition\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1a\n" +
	"\bsettings\x18\t \x01(\tR\bsettings\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAtB\r\n" +
	"\v_departmentB\v\n" +
	"\t_position2\x99\x04\n" +
	"\vAuthService\x120\n" +
	"\x05GetMe\x12\x12.auth.GetMeRequest\x1a\x13.auth.GetMeResponse\x12E\n" +
	"\fSignupClient\x12\x19.auth.SignupClientRequest\x1a\x1a.auth.SignupClientResponse\x12N\n" +
	"\x0fListClientUsers\x12\x1c.auth.ListClientUsersRequest\x1a\x1d.auth.ListClientUsersResponse\x12H\n" +
	"\rGetClientUser\x12\x1a.auth.GetClientUserRequest\x1a\x1b.auth.GetClientUserResponse\x12Q\n" +
	"\x10CreateClientUser\x12\x1d.auth.CreateClientUserRequest\x1a\x1e.auth.CreateClientUserResponse\x12Q\n" +
	"\x10UpdateClientUser\x12\x1d.auth.UpdateClientUserRequest\x1a\x1e.auth.UpdateClientUserResponse\x12Q\n" +
	"\x10DeleteClientUser\x12\x1d.auth.DeleteClientUserRequest\x1a\x1e.auth.DeleteClientUserResponseB\x1fZ\x1dcontract-pro-suite/proto/authb\x06proto3"

var (
	file_proto_auth_auth_proto_rawDescOnce sync.Once
	file_proto_auth_auth_proto_rawDescData []byte
)

func file_proto_auth_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_auth_proto_rawDesc), len(file_proto_auth_auth_proto_rawDesc)))
	})
	return file_proto_auth_auth_proto_rawDescData
}

var file_proto_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_auth_auth_proto_goTypes = []any{
	(*GetMeRequest)(nil),             // 0: auth.GetMeRequest
	(*GetMeResponse)(nil),            // 1: auth.GetMeResponse
	(*SignupClientRequest)(nil),      // 2: auth.SignupClientRequest
	(*SignupClientResponse)(nil),     // 3: auth.SignupClientResponse
	(*ListClientUsersRequest)(nil),   // 4: auth.ListClientUsersRequest
	(*ListClientUsersResponse)(nil),  // 5: auth.ListClientUsersResponse
	(*GetClientUserRequest)(nil),     // 6: auth.GetClientUserRequest
	(*GetClientUserResponse)(nil),    // 7: auth.GetClientUserResponse
	(*CreateClientUserRequest)(nil),  // 8: auth.CreateClientUserRequest
	(*CreateClientUserResponse)(nil), // 9: auth.CreateClientUserResponse
	(*UpdateClientUserRequest)(nil),  // 10: auth.UpdateClientUserRequest
	(*UpdateClientUserResponse)(nil), // 11: auth.UpdateClientUserResponse
	(*DeleteClientUserRequest)(nil),  // 12: auth.DeleteClientUserRequest
	(*DeleteClientUserResponse)(nil), // 13: auth.DeleteClientUserResponse
	(*ClientUser)(nil),               // 14: auth.ClientUser
}
var file_proto_auth_auth_proto_depIdxs = []int32{
	14, // 0: auth.ListClientUsersResponse.users:type_name -> auth.ClientUser
	14, // 1: auth.GetClientUserResponse.user:type_name -> auth.ClientUser
	14, // 2: auth.CreateClientUserResponse.user:type_name -> auth.ClientUser
	14, // 3: auth.UpdateClientUserResponse.user:type_name -> auth.ClientUser
	0,  // 4: auth.AuthService.GetMe:input_type -> auth.GetMeRequest
	2,  // 5: auth.AuthService.SignupClient:input_type -> auth.SignupClientRequest
	4,  // 6: auth.AuthService.ListClientUsers:input_type -> auth.ListClientUsersRequest
	6,  // 7: auth.AuthService.GetClientUser:input_type -> auth.GetClientUserRequest
	8,  // 8: auth.AuthService.CreateClientUser:input_type -> auth.CreateClientUserRequest
	10, // 9: auth.AuthService.UpdateClientUser:input_type -> auth.UpdateClientUserRequest
	12, // 10: auth.AuthService.DeleteClientUser:input_type -> auth.DeleteClientUserRequest
	1,  // 11: auth.AuthService.GetMe:output_type -> auth.GetMeResponse
	3,  // 12: auth.AuthService.SignupClient:output_type -> auth.SignupClientResponse
	5,  // 13: auth.AuthService.ListClientUsers:output_type -> auth.ListClientUsersResponse
	7,  // 14: auth.AuthService.GetClientUser:output_type -> auth.GetClientUserResponse
	9,  // 15: auth.AuthService.CreateClientUser:output_type -> auth.CreateClientUserResponse
	11, // 16: auth.AuthService.UpdateClientUser:output_type -> auth.UpdateClientUserResponse
	13, // 17: auth.AuthService.DeleteClientUser:output_type -> auth.DeleteClientUserResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_auth_auth_proto_init() }
func file_proto_auth_auth_proto_init() {
	if File_proto_auth_auth_proto != nil {
		return
	}
	file_proto_auth_auth_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_auth_auth_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_auth_auth_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_auth_auth_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_auth_auth_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_auth_proto_rawDesc), len(file_proto_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_auth_proto = out.File
	file_proto_auth_auth_proto_goTypes = nil
	file_proto_auth_auth_proto_depIdxs = nil
}
