// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    slug,
    company_code,
    name,
    e_sign_mode,
    retention_default_months,
    status,
    settings
) VALUES (
    $1, NULLIF($2, ''), $3, $4, $5, $6, $7
)
RETURNING client_id, slug, company_code, name, e_sign_mode, retention_default_months, status, settings, deleted_at, deleted_by, created_at, updated_at
`

type CreateClientParams struct {
	Slug                   string      `json:"slug"`
	Column2                interface{} `json:"column_2"`
	Name                   string      `json:"name"`
	ESignMode              string      `json:"e_sign_mode"`
	RetentionDefaultMonths int32       `json:"retention_default_months"`
	Status                 string      `json:"status"`
	Settings               []byte      `json:"settings"`
}

// :param company_code text
func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Slug,
		arg.Column2,
		arg.Name,
		arg.ESignMode,
		arg.RetentionDefaultMonths,
		arg.Status,
		arg.Settings,
	)
	var i Client
	err := row.Scan(
		&i.ClientID,
		&i.Slug,
		&i.CompanyCode,
		&i.Name,
		&i.ESignMode,
		&i.RetentionDefaultMonths,
		&i.Status,
		&i.Settings,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
UPDATE clients
SET
    deleted_at = now(),
    deleted_by = $2,
    updated_at = now()
WHERE client_id = $1
  AND deleted_at IS NULL
`

type DeleteClientParams struct {
	ClientID  pgtype.UUID `json:"client_id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) error {
	_, err := q.db.Exec(ctx, deleteClient, arg.ClientID, arg.DeletedBy)
	return err
}

const getClient = `-- name: GetClient :one
SELECT client_id, slug, company_code, name, e_sign_mode, retention_default_months, status, settings, deleted_at, deleted_by, created_at, updated_at FROM clients
WHERE client_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetClient(ctx context.Context, clientID pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, clientID)
	var i Client
	err := row.Scan(
		&i.ClientID,
		&i.Slug,
		&i.CompanyCode,
		&i.Name,
		&i.ESignMode,
		&i.RetentionDefaultMonths,
		&i.Status,
		&i.Settings,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByCompanyCode = `-- name: GetClientByCompanyCode :one
SELECT client_id, slug, company_code, name, e_sign_mode, retention_default_months, status, settings, deleted_at, deleted_by, created_at, updated_at FROM clients
WHERE company_code = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetClientByCompanyCode(ctx context.Context, companyCode pgtype.Text) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByCompanyCode, companyCode)
	var i Client
	err := row.Scan(
		&i.ClientID,
		&i.Slug,
		&i.CompanyCode,
		&i.Name,
		&i.ESignMode,
		&i.RetentionDefaultMonths,
		&i.Status,
		&i.Settings,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientBySlug = `-- name: GetClientBySlug :one
SELECT client_id, slug, company_code, name, e_sign_mode, retention_default_months, status, settings, deleted_at, deleted_by, created_at, updated_at FROM clients
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetClientBySlug(ctx context.Context, slug string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientBySlug, slug)
	var i Client
	err := row.Scan(
		&i.ClientID,
		&i.Slug,
		&i.CompanyCode,
		&i.Name,
		&i.ESignMode,
		&i.RetentionDefaultMonths,
		&i.Status,
		&i.Settings,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT client_id, slug, company_code, name, e_sign_mode, retention_default_months, status, settings, deleted_at, deleted_by, created_at, updated_at FROM clients
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListClientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ClientID,
			&i.Slug,
			&i.CompanyCode,
			&i.Name,
			&i.ESignMode,
			&i.RetentionDefaultMonths,
			&i.Status,
			&i.Settings,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET
    slug = COALESCE($2, slug),
    company_code = COALESCE($3, company_code),
    name = COALESCE($4, name),
    e_sign_mode = COALESCE($5, e_sign_mode),
    retention_default_months = COALESCE($6, retention_default_months),
    status = COALESCE($7, status),
    settings = COALESCE($8, settings),
    updated_at = now()
WHERE client_id = $1
  AND deleted_at IS NULL
RETURNING client_id, slug, company_code, name, e_sign_mode, retention_default_months, status, settings, deleted_at, deleted_by, created_at, updated_at
`

type UpdateClientParams struct {
	ClientID               pgtype.UUID `json:"client_id"`
	Slug                   string      `json:"slug"`
	CompanyCode            pgtype.Text `json:"company_code"`
	Name                   string      `json:"name"`
	ESignMode              string      `json:"e_sign_mode"`
	RetentionDefaultMonths int32       `json:"retention_default_months"`
	Status                 string      `json:"status"`
	Settings               []byte      `json:"settings"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ClientID,
		arg.Slug,
		arg.CompanyCode,
		arg.Name,
		arg.ESignMode,
		arg.RetentionDefaultMonths,
		arg.Status,
		arg.Settings,
	)
	var i Client
	err := row.Scan(
		&i.ClientID,
		&i.Slug,
		&i.CompanyCode,
		&i.Name,
		&i.ESignMode,
		&i.RetentionDefaultMonths,
		&i.Status,
		&i.Settings,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
