// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClientRole = `-- name: CreateClientRole :one
INSERT INTO client_roles (
    role_id,
    client_id,
    code,
    name,
    description,
    is_system
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING role_id, client_id, code, name, description, is_system, deleted_at, deleted_by, created_at
`

type CreateClientRoleParams struct {
	RoleID      pgtype.UUID `json:"role_id"`
	ClientID    pgtype.UUID `json:"client_id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsSystem    bool        `json:"is_system"`
}

func (q *Queries) CreateClientRole(ctx context.Context, arg CreateClientRoleParams) (ClientRole, error) {
	row := q.db.QueryRow(ctx, createClientRole,
		arg.RoleID,
		arg.ClientID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IsSystem,
	)
	var i ClientRole
	err := row.Scan(
		&i.RoleID,
		&i.ClientID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClientRole = `-- name: DeleteClientRole :exec
UPDATE client_roles
SET
    deleted_at = now(),
    deleted_by = $2
WHERE role_id = $1
  AND deleted_at IS NULL
  AND is_system = false
`

type DeleteClientRoleParams struct {
	RoleID    pgtype.UUID `json:"role_id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteClientRole(ctx context.Context, arg DeleteClientRoleParams) error {
	_, err := q.db.Exec(ctx, deleteClientRole, arg.RoleID, arg.DeletedBy)
	return err
}

const getClientRole = `-- name: GetClientRole :one
SELECT role_id, client_id, code, name, description, is_system, deleted_at, deleted_by, created_at FROM client_roles
WHERE role_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetClientRole(ctx context.Context, roleID pgtype.UUID) (ClientRole, error) {
	row := q.db.QueryRow(ctx, getClientRole, roleID)
	var i ClientRole
	err := row.Scan(
		&i.RoleID,
		&i.ClientID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getClientRoleByCode = `-- name: GetClientRoleByCode :one
SELECT role_id, client_id, code, name, description, is_system, deleted_at, deleted_by, created_at FROM client_roles
WHERE client_id = $1
  AND code = $2
  AND deleted_at IS NULL
`

type GetClientRoleByCodeParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetClientRoleByCode(ctx context.Context, arg GetClientRoleByCodeParams) (ClientRole, error) {
	row := q.db.QueryRow(ctx, getClientRoleByCode, arg.ClientID, arg.Code)
	var i ClientRole
	err := row.Scan(
		&i.RoleID,
		&i.ClientID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listClientRoles = `-- name: ListClientRoles :many
SELECT role_id, client_id, code, name, description, is_system, deleted_at, deleted_by, created_at FROM client_roles
WHERE client_id = $1
  AND deleted_at IS NULL
ORDER BY is_system DESC, created_at ASC
`

func (q *Queries) ListClientRoles(ctx context.Context, clientID pgtype.UUID) ([]ClientRole, error) {
	rows, err := q.db.Query(ctx, listClientRoles, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientRole{}
	for rows.Next() {
		var i ClientRole
		if err := rows.Scan(
			&i.RoleID,
			&i.ClientID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientRole = `-- name: UpdateClientRole :one
UPDATE client_roles
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description)
WHERE role_id = $1
  AND deleted_at IS NULL
  AND is_system = false  -- システムロールは更新不可
RETURNING role_id, client_id, code, name, description, is_system, deleted_at, deleted_by, created_at
`

type UpdateClientRoleParams struct {
	RoleID      pgtype.UUID `json:"role_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateClientRole(ctx context.Context, arg UpdateClientRoleParams) (ClientRole, error) {
	row := q.db.QueryRow(ctx, updateClientRole, arg.RoleID, arg.Name, arg.Description)
	var i ClientRole
	err := row.Scan(
		&i.RoleID,
		&i.ClientID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
	)
	return i, err
}
