// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_role_permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClientRolePermission = `-- name: CreateClientRolePermission :one
INSERT INTO client_role_permissions (
    role_id,
    feature,
    action,
    granted,
    conditions
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING role_id, feature, action, granted, conditions, deleted_at, deleted_by, created_at
`

type CreateClientRolePermissionParams struct {
	RoleID     pgtype.UUID `json:"role_id"`
	Feature    string      `json:"feature"`
	Action     string      `json:"action"`
	Granted    bool        `json:"granted"`
	Conditions []byte      `json:"conditions"`
}

func (q *Queries) CreateClientRolePermission(ctx context.Context, arg CreateClientRolePermissionParams) (ClientRolePermission, error) {
	row := q.db.QueryRow(ctx, createClientRolePermission,
		arg.RoleID,
		arg.Feature,
		arg.Action,
		arg.Granted,
		arg.Conditions,
	)
	var i ClientRolePermission
	err := row.Scan(
		&i.RoleID,
		&i.Feature,
		&i.Action,
		&i.Granted,
		&i.Conditions,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClientRolePermission = `-- name: DeleteClientRolePermission :exec
UPDATE client_role_permissions
SET
    deleted_at = now(),
    deleted_by = $4
WHERE role_id = $1
  AND feature = $2
  AND action = $3
  AND deleted_at IS NULL
`

type DeleteClientRolePermissionParams struct {
	RoleID    pgtype.UUID `json:"role_id"`
	Feature   string      `json:"feature"`
	Action    string      `json:"action"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteClientRolePermission(ctx context.Context, arg DeleteClientRolePermissionParams) error {
	_, err := q.db.Exec(ctx, deleteClientRolePermission,
		arg.RoleID,
		arg.Feature,
		arg.Action,
		arg.DeletedBy,
	)
	return err
}

const deleteClientRolePermissionsByRoleID = `-- name: DeleteClientRolePermissionsByRoleID :exec
UPDATE client_role_permissions
SET
    deleted_at = now(),
    deleted_by = $2
WHERE role_id = $1
  AND deleted_at IS NULL
`

type DeleteClientRolePermissionsByRoleIDParams struct {
	RoleID    pgtype.UUID `json:"role_id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteClientRolePermissionsByRoleID(ctx context.Context, arg DeleteClientRolePermissionsByRoleIDParams) error {
	_, err := q.db.Exec(ctx, deleteClientRolePermissionsByRoleID, arg.RoleID, arg.DeletedBy)
	return err
}

const getClientRolePermission = `-- name: GetClientRolePermission :one
SELECT role_id, feature, action, granted, conditions, deleted_at, deleted_by, created_at FROM client_role_permissions
WHERE role_id = $1
  AND feature = $2
  AND action = $3
  AND deleted_at IS NULL
`

type GetClientRolePermissionParams struct {
	RoleID  pgtype.UUID `json:"role_id"`
	Feature string      `json:"feature"`
	Action  string      `json:"action"`
}

func (q *Queries) GetClientRolePermission(ctx context.Context, arg GetClientRolePermissionParams) (ClientRolePermission, error) {
	row := q.db.QueryRow(ctx, getClientRolePermission, arg.RoleID, arg.Feature, arg.Action)
	var i ClientRolePermission
	err := row.Scan(
		&i.RoleID,
		&i.Feature,
		&i.Action,
		&i.Granted,
		&i.Conditions,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getClientRolePermissionsByFeatureAndAction = `-- name: GetClientRolePermissionsByFeatureAndAction :many
SELECT role_id, feature, action, granted, conditions, deleted_at, deleted_by, created_at FROM client_role_permissions
WHERE role_id = $1
  AND feature = $2
  AND action = $3
  AND deleted_at IS NULL
  AND granted = true
`

type GetClientRolePermissionsByFeatureAndActionParams struct {
	RoleID  pgtype.UUID `json:"role_id"`
	Feature string      `json:"feature"`
	Action  string      `json:"action"`
}

func (q *Queries) GetClientRolePermissionsByFeatureAndAction(ctx context.Context, arg GetClientRolePermissionsByFeatureAndActionParams) ([]ClientRolePermission, error) {
	rows, err := q.db.Query(ctx, getClientRolePermissionsByFeatureAndAction, arg.RoleID, arg.Feature, arg.Action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientRolePermission{}
	for rows.Next() {
		var i ClientRolePermission
		if err := rows.Scan(
			&i.RoleID,
			&i.Feature,
			&i.Action,
			&i.Granted,
			&i.Conditions,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientRolePermissionsByRoleID = `-- name: GetClientRolePermissionsByRoleID :many
SELECT role_id, feature, action, granted, conditions, deleted_at, deleted_by, created_at FROM client_role_permissions
WHERE role_id = $1
  AND deleted_at IS NULL
ORDER BY feature, action
`

func (q *Queries) GetClientRolePermissionsByRoleID(ctx context.Context, roleID pgtype.UUID) ([]ClientRolePermission, error) {
	rows, err := q.db.Query(ctx, getClientRolePermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientRolePermission{}
	for rows.Next() {
		var i ClientRolePermission
		if err := rows.Scan(
			&i.RoleID,
			&i.Feature,
			&i.Action,
			&i.Granted,
			&i.Conditions,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientRolePermission = `-- name: UpdateClientRolePermission :one
UPDATE client_role_permissions
SET
    granted = COALESCE($4, granted),
    conditions = COALESCE($5, conditions)
WHERE role_id = $1
  AND feature = $2
  AND action = $3
  AND deleted_at IS NULL
RETURNING role_id, feature, action, granted, conditions, deleted_at, deleted_by, created_at
`

type UpdateClientRolePermissionParams struct {
	RoleID     pgtype.UUID `json:"role_id"`
	Feature    string      `json:"feature"`
	Action     string      `json:"action"`
	Granted    bool        `json:"granted"`
	Conditions []byte      `json:"conditions"`
}

func (q *Queries) UpdateClientRolePermission(ctx context.Context, arg UpdateClientRolePermissionParams) (ClientRolePermission, error) {
	row := q.db.QueryRow(ctx, updateClientRolePermission,
		arg.RoleID,
		arg.Feature,
		arg.Action,
		arg.Granted,
		arg.Conditions,
	)
	var i ClientRolePermission
	err := row.Scan(
		&i.RoleID,
		&i.Feature,
		&i.Action,
		&i.Granted,
		&i.Conditions,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
	)
	return i, err
}
