// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ClientID               pgtype.UUID        `json:"client_id"`
	Slug                   string             `json:"slug"`
	CompanyCode            pgtype.Text        `json:"company_code"`
	Name                   string             `json:"name"`
	ESignMode              string             `json:"e_sign_mode"`
	RetentionDefaultMonths int32              `json:"retention_default_months"`
	Status                 string             `json:"status"`
	Settings               []byte             `json:"settings"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy              pgtype.UUID        `json:"deleted_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type ClientRole struct {
	RoleID      pgtype.UUID        `json:"role_id"`
	ClientID    pgtype.UUID        `json:"client_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsSystem    bool               `json:"is_system"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ClientRolePermission struct {
	RoleID     pgtype.UUID        `json:"role_id"`
	Feature    string             `json:"feature"`
	Action     string             `json:"action"`
	Granted    bool               `json:"granted"`
	Conditions []byte             `json:"conditions"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy  pgtype.UUID        `json:"deleted_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ClientUser struct {
	ClientUserID pgtype.UUID        `json:"client_user_id"`
	ClientID     pgtype.UUID        `json:"client_id"`
	Email        string             `json:"email"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	Department   pgtype.Text        `json:"department"`
	Position     pgtype.Text        `json:"position"`
	Settings     []byte             `json:"settings"`
	Status       string             `json:"status"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ClientUserRole struct {
	ClientID     pgtype.UUID        `json:"client_id"`
	ClientUserID pgtype.UUID        `json:"client_user_id"`
	RoleID       pgtype.UUID        `json:"role_id"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
}

type Operator struct {
	OperatorID        pgtype.UUID        `json:"operator_id"`
	Email             string             `json:"email"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	Status            string             `json:"status"`
	MfaEnabled        bool               `json:"mfa_enabled"`
	PasswordHash      pgtype.Text        `json:"password_hash"`
	Salt              pgtype.Text        `json:"salt"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy         pgtype.UUID        `json:"deleted_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type OperatorAssignment struct {
	ClientID     pgtype.UUID        `json:"client_id"`
	OperatorID   pgtype.UUID        `json:"operator_id"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
	UnassignedAt pgtype.Timestamptz `json:"unassigned_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
}
